apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-v2
  labels:
    app: myapp
spec:
  containers:
    - name : nginx-container
      image: nginx
      command: ["sleep"]
      args: ["5"]
      envFrom:
        - secretRef:
            name: app-secret
      env:
        - name: PROPERTY1
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: property1
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: app-config

        