apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-secret
  labels:
    app: myapp
spec:
  containers:
    - name : nginx-container
      image: nginx
      command: ["sleep"]
      args: ["5"]
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        